### ISSUE TITLE
Feature Request: OLED

### ISSUE THREAD

**Issue by EBUJOLD** [xinabox/FlashTool#2]
We've been working with the FlashTool and it seems to work really well.

Something that I think would be really nice to add is a some text on the OLED that would give feedback to students. 

* Display the xChips Wifi address while the chip is being configured and then  "Connection Established"
When we were trying to connect a bunch of chips at the same time we had to do them one at a time so that the wifi addresses didn't get mixed up. This took a long time. 

*  Name/index name when it's sending data for easy identification. 

*  And any debugging messages would also be excellent to have.

**Comment by brendanvanbreda** [comment]
Hi @EBUJOLD we currently adding to a new revision and improving the stability of the current systems watch this space for a new release.

**Comment by EBUJOLD** [comment]
Thank you for the quick response.

We thought these would be useful new features for teachers. 

What is the best place to request features and bugs for future reference?

**Comment by gotfredsen** [comment]
@EBUJOLD I set up this website for ideas. I never tried it, but I thought your idea was great, so lets give it a try: https://xinabox.ideascale.com
Once you guys and we have played with it for a while, we will let everybody else know about it.

**Comment by gotfredsen** [comment]
@EBUJOLD New release available: https://github.com/xinabox/FlashTool/releases/tag/v1.1-beta.3 please check out the OLED information.
